### ISSUE TITLE
QRencode permission issue for linked account

### ISSUE THREAD

**Issue by zalmoxis** [hoehermann/purple-signald#36]
When starting pidgin you may get an error about qrencode failing to execute. In my case I have apparmor on debian and the default profile for pidgin does not allow that execution.
The fix is adding this line
`/usr/bin/qrencode rix,`
in the appropriate place in the file:
`/etc/apparmor.d/usr.bin.pidgin`

I am creating this issue in case someone else has the same problem. It is very not obvious that it would be an app armor issue and I figured that out by finding the "system" call in the source.

**Comment by hoehermann** [comment]
Thank you for the notice. The way the linking procedure is implemented is far from optimal. You can check out the sister-project [purple-signal](https://github.com/hoehermann/purple-signal). The implementation is way cleaner, but I have not added all of this plug-in's features, yet.

**Comment by blacklight** [comment]
I'm experiencing the same issue on Arch+bitlbee.

After a bit of debugging I've noticed that the [`qrencode system()` call](https://github.com/hoehermann/libpurple-signald/blob/master/link.c#L93) returns a failure even though the image was correctly generated. Not sure why this is the case (permissions maybe?) because I can't replicate it from the shell, and I suppose that the plugin would need to use something better than a `system()` to capture the stderr to debug it.

Even when I disable the check on the system result, the plugin still hangs without showing any QR code. My hypothesis is that [`purple_request_field_image_new`](https://github.com/hoehermann/libpurple-signald/blob/master/link.c#L53) used in `signald_scan_qrcode` isn't available in Bitlbee, therefore the plugin just hangs waiting for data.

I guess that something along the lines of [what's been done in `purple-gowhatsapp`](https://github.com/hoehermann/purple-gowhatsapp/commit/6880aaac0ff133697ce9022cc4b525344470e483) (i.e. cleverly figure out whether the purple interface provides UI capabilities, and display the QR code in text format if that's not the case) should solve the problem.

I could spend some time on a PR if it's not already been tackled by other devs, but first I'd like to know which Signal plugin is currently advised/maintained (this or `purple-signal`?)

**Comment by hoehermann** [comment]
Thank you for your interest.

> I'd like to know which Signal plugin is currently advised/maintained (this or purple-signal?)

Currently, neither of the plug-ins is maintained. :(  
I wanted win32 compatibility and I like the tighter coupling in purple-signal, but the code is more involved so I am on my own there.  
purple-signald suffers from problems with permissions, missing error handling due to loose coupling (like described here), severe defects in group and contact handling and the internal protocol changes almost every Tuesday. There are some contributions by ttlmax, so purple-signald is the safer bet, I guess.

More generally speaking, I think purple-signald needs a re-write – just as purple-gowhatsapp became purple-whatsmeow. For example, the QR-code-generation should be done by something like https://raymii.org/s/software/Cpp_generate_qr_code_and_write_it_to_png_scaled.html.

I have been quite busy with purple-whatsmeow and I cannot tell you if or when I will turn my attention towards purple-signald again.

**Comment by hoehermann** [comment]
72fb734 fixes this issue.
