### ISSUE TITLE
Contacts Disappear After Quitting Weechat

### ISSUE THREAD

**Issue by heywoodlh** [hoehermann/purple-signald#50]
I use Weechat as my client to connect to Bitlbee+Libpurple.

After quitting Weechat and reopening it none of my contacts in signald show up. The contacts are still in signald when I connect to the socket manually and list the contacts.

Restarting signald and bitlbee fixes the problem. 

Is there any way to get the contacts to show back up without restarting the services?

**Comment by ttlmax** [comment]
Have you tried the account action "Update Contacts"?

**Comment by heywoodlh** [comment]
@ttlmax Sorry for the delay in response.

How do I run that action?

**Comment by hoehermann** [comment]
In the last weeks, I made some changes on how contacts are handled. Is this still an issue with the version in the master branch?

In Pidgin, the "Update Contacts" action appears as a button in the account's menu. Since I develop against Pigdin and do not run a bitlbee server, I have no idea how to access that action in bitlbee.

**Comment by hoehermann** [comment]
Closing due to lack of response.
