### ISSUE TITLE
Core dump on pidgin enable

### ISSUE THREAD

**Issue by strufepub** [hoehermann/purple-signald#57]
I've had some trouble with signald/libpurple-signald for some time, now, as libpurple-signald kept disconnecting (may be 1-2 months). It seems as though it crashed whenever there had been offline-messages, and after clicking re-enable dozens of times (to seemingly download each of the offline-message one by one), it would run comparatively stable (until there again were offline-messages).

I've realized there were some changes committed today, so pulled, made, installed -- and now I first of all still get "signald reported an unexpected error. View the console output in debug mode for more information." 

When starting pidgin, but pushing re-enable now directly leads to pidgin crashing completely:

    $ pidgin 
    <click "re-enable">
    *** buffer overflow detected ***: terminated
    Aborted (core dumped)

The syslog previously complained about a couple of issues

    Oct  3 17:39:55 diskordia signald[969]: 17:39:55.879 [connection-pid-6450] INFO  io.finn.signald.clientp
    rotocol.ClientConnection - Client connected
    Oct  3 17:39:56 diskordia signald[969]: 17:39:56.879 [Thread-193] INFO  io.finn.signald.clientprotocol.C
    lientConnection - signald received a request with no version. This will stop working in a future version
     of signald. Please update your client. Client authors, see https://signald.org/articles/protocol-versio
    ning/
    Oct  3 17:39:57 diskordia systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
    Oct  3 17:39:59 diskordia signald[969]: 17:39:59.102 [Thread-199] ERROR io.finn.signald.clientprotocol.C
    lientConnection - Catching
    Oct  3 17:39:59 diskordia signald[969]: java.lang.NullPointerException: null
    Oct  3 17:39:59 diskordia signald[969]: #011at org.whispersystems.libsignal.util.guava.Preconditions.che
    ckNotNull(Preconditions.java:189) ~[signal-client-java-x86_64-unknown-linux-gnu-0.9.0.jar:?]
    Oct  3 17:39:59 diskordia signald[969]: #011at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:34) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_27.jar:?]
    Oct  3 17:39:59 diskordia signald[969]: #011at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:47) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_27.jar:?]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.clientprotocol.v1.JsonAddress.getSignalServiceAddress(JsonAddress.java:63) ~[signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.storage.GroupInfo.getMembers(GroupInfo.java:39) ~[signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.clientprotocol.v1.JsonGroupInfo.<init>(JsonGroupInfo.java:65) ~[signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.JsonGroupList.<init>(JsonGroupList.java:35) ~[signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.LegacySocketHandler.listGroups(LegacySocketHandler.java:466) ~[signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.LegacySocketHandler.handleRequest(LegacySocketHandler.java:143) ~[signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:157) [signald.jar:unspecified]
    Oct  3 17:39:59 diskordia signald[969]: #011at java.lang.Thread.run(Thread.java:829) [?:?]
    Oct  3 17:39:59 diskordia signald[969]: 17:39:59.129 [connection-pid-6450] INFO  io.finn.signald.MessageReceiver - Last client for **********************************3d unsubscribed, shutting down message pipe
    Oct  3 17:39:59 diskordia signald[969]: 17:39:59.129 [Thread-200] INFO  io.finn.signald.clientprotocol.ClientConnection - signald received a request with no version. This will stop working in a future version of signald. Please update your client. Client authors, see https://signald.org/articles/protocol-versioning/
    Oct  3 17:39:59 diskordia signald[969]: 17:39:59.129 [connection-pid-6450] INFO  io.finn.signald.clientprotocol.ClientConnection - Client disconnected

But now there's not even a message in the syslog (so that's an improvement, I guess ;-D)

Having signal run in pidgin was really useful, I hope we'll get it back to work like it did before! :)

Not sure if there's anything I can do to help?

**Comment by hoehermann** [comment]
Thank you for the report. The crucial part most likely is `signald received a request with no version. (…)`, which has already been filed as issue #54. I expect the plug-in not to work. A crash however should not occur.

When I started this project, I chose signald as a middleware because it looked like it would provide a useful level of abstraction from the bare signal library. Currently, however, I am annoyed by the amount of protocol changes (not only signald but also signal itself). My willingness to adapt my plug-in every other month has been reduced close to zero. So no estimate on when I may fix this. Contributions are welcome.

**Comment by ttlmax** [comment]
Regarding the `signald received a request with no version` message, I think that these are warning messages and the request is still processed. At least I am working with the plugin on a (very) regular basis and offline messages are no problem. What I see sometimes that the plugin shows an connection error after pidgin's startup but then reconnect after some time and starts downloading the offline messages.

Are you linking to a master device when using the plugin? If yes, have you tried to remove the linked device on your master device and re-link?

Shifting all request to version 2 (from version 1 or no explicitly specified version, which causes the warnings) actually requires quite some effort since the v2 requests and structures have different parameters.

**Comment by strufepub** [comment]
Thanks guys, I just tried removing and re-linking and pulled today's version and everybody seems to work again.

Thanks a lot!
