### ISSUE TITLE
Key Issue in your Git Repo

### ISSUE THREAD

**Issue by radasbona** [hoehermann/purple-signald#76]
Hi.
Here is my output: 

git clone --recurse-submodules git@github.com:hoehermann/purple-signald.git
Klone nach 'purple-signald' ...
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.

**Comment by DanielSiepmann** [comment]
I don't think that's an issue with this repo but an issue with your GitHub setup. Looks like you clone via ssh but didn't provide the ssh key you've setup within GitHub?

Did you try without `--recurse-submodules`? Does that end up in the same issue? Maybe try to clone via https `https://github.com/hoehermann/purple-signald.git` instead of ssh `git@github.com:hoehermann/purple-signald.git` to verify my idea.

**Comment by radasbona** [comment]
> but didn't provide the ssh key you've setup within GitHub? 

Yes, i forgot i inserted one. a long time ago. Sorry.
